import { defineConfig } from 'vite';

// No laravel-vite-plugin / manifest here — Razor views reference the fixed output filenames
// directly with the asp-append-version tag helper for cache-busting instead of manifest hashes.
export default defineConfig({
  root: '.',
  // Everything Vite builds is served from /build/ (asp-append-version references ~/build/app.css
  // etc. directly), but Vite's own default base is site-root — without this, any URL Vite
  // generates for you (e.g. a `?url` import of a binary asset) comes out missing the /build/
  // prefix and 404s, even though app.js/app.css work fine since those paths are hardcoded by
  // hand in _Layout.cshtml rather than generated by Vite.
  base: '/build/',
  build: {
    outDir: '../wwwroot/build',
    emptyOutDir: true,
    rollupOptions: {
      input: 'resources/js/app.js',
      output: {
        entryFileNames: 'app.js',
        // Only app.css needs a fixed name (_Layout.cshtml references it directly). Every other
        // asset — including any binary asset pulled in by a JS import, e.g. intl-tel-input's
        // flag sprite — gets a real hashed name instead of the old blanket 'app.[ext]' pattern,
        // which silently collapsed multiple same-extension assets (two different .webp files)
        // onto the same output filename and left the second import resolving to the first
        // asset's URL.
        assetFileNames: (assetInfo) =>
          assetInfo.name === 'app.css' ? 'app.css' : 'assets/[name]-[hash][extname]',
      },
    },
  },
  resolve: {
    alias: {
      '@': '/resources/js',
    },
  },
});
